theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag

markdown: CommonMarkGhPages

commonmark:
  options:
    - "UNSAFE"

url: https://fwextensions.github.io/QuicKey

title: QuicKey | Jump between recent tabs in Chrome via keyboard or menu

description: Have dozens of tabs open? Quickly jump between them with QuicKey, a Chrome extension that adds keyboard shortcuts to switch tabs with a Quicksilver-style search or a most recently used (MRU) menu.

tagline: Add keyboard shortcuts to switch tabs with a Quicksilver-style search or a most recently used (MRU) menu

image: /img/search-box-open.png

logo: /img/icon-300.png

google_analytics: UA-108153491-1

twitter:
  username: fwextensions

author:
  name: John Dunning
  twitter: fwextensions

rootPath: /QuicKey
